---
Description: Stack
Parameters:
  DreamFactoryAccount:
    Type: String
    Description: DreamFactory
    Default: '803335938539'
  ExternalId:
    Type: String
    Description: Id used to assume the Athena/CUR Role
  DatabaseName:
    Type: String
    Default: 'dreamfactorydb'
    Description: Athena Database Name - to access billing data

Resources:
  CURStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://github.com/dream-factory-code/cost-optimization/blob/master/dreamfactory-cur.yaml
      Parameters:
        ExternalId: !Ref ExternalId
        DatabaseName: !Ref DatabaseName
      Tags:
        - Key: 'dreamfactory'
          Value: 'DreamFactory Infrastructure'
  CURRoleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://github.com/dream-factory-code/cost-optimization/blob/master/cur-role.yaml
      Parameters:
        ExternalId: !Ref ExternalId
        DreamFactoryAccount: !Ref DreamFactoryAccount
        DatabaseName: !Ref DatabaseName
    Tags:
      - Key: 'dreamfactory'
        Value: 'DreamFactory CloudFix Infrastructure'
