Description: AWS Role to access CUR Report.
Parameters:
  ExternalId:
    Type: String
    Description: ExternalId
  DreamFactoryAccount:
    Type: String
    Description: DreamFactory Account
  DatabaseName:
    Type: String
    Default: 'dreamfactorydb'
    Description: Athena Database Name
Resources:
  DreamFactoryAthenaQueryExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
          Statement:
            - Action: 'sts:AssumeRole'
              Condition:
                StringEquals:
                  'sts:ExternalId': !Ref ExternalId
              Effect: Allow
              Principal:
                AWS: !Join 
                  - ''
                  - - 'arn:'
                    - !Ref 'AWS::Partition'
                    - ':iam::'
                    - !Ref DreamFactoryAccount
                    - ':root'
          Version: 2012-10-17
      MaxSessionDuration: 14400
      Policies:
          - PolicyDocument:
              Statement:
                - Action: 's3:*'
                  Effect: Allow
                  Resource:
                    - !Join 
                      - ''
                      - - 'arn:aws:s3:::'
                        - 'dreamfactory-cur-'
                        - !Ref 'AWS::AccountId'                        
                    - !Join 
                      - ''
                      - - 'arn:aws:s3:::'
                        - 'dreamfactory-cur-'
                        - !Ref 'AWS::AccountId'
                        - '/*'
                - Action:
                    - 'athena:StartQueryExecution'
                    - 'athena:GetQueryExecution'
                    - 'athena:GetQueryResults'
                  Effect: Allow
                  Resource: !Join 
                    - ''
                    - - 'arn:aws:athena:*:'
                      - !Ref 'AWS::AccountId'
                      - ':workgroup/DreamFactoryWorkspace'
                - Action: 'glue:*'
                  Effect: Allow
                  Resource:
                    - !Join 
                      - ''
                      - - 'arn:aws:glue:*:'
                        - !Ref 'AWS::AccountId'
                        - ':catalog'
                    - !Join 
                      - ''
                      - - 'arn:aws:glue:*:'
                        - !Ref 'AWS::AccountId'
                        - ':database/'
                        - !Ref DatabaseName
                    - !Join 
                      - ''
                      - - 'arn:aws:glue:*:'
                        - !Ref 'AWS::AccountId'
                        - ':table/'
                        - !Ref DatabaseName
                        - '/*'
                    - !Join 
                      - ''
                      - - 'arn:aws:glue:*:'
                        - !Ref 'AWS::AccountId'
                        - ':userDefinedFunction/'
                        - !Ref DatabaseName
                        - '/*'
              Version: 2012-10-17
            PolicyName: core
      RoleName: dreamfactory-athena-query-execution-role
